-- ============================================================
-- Script de base de datos Oracle - Sistema de Biblioteca
-- DSY2207 - Desarrollo Cloud Native II
-- ============================================================

-- Tabla de Usuarios
CREATE TABLE usuarios (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR2(100)  NOT NULL,
    apellido    VARCHAR2(100)  NOT NULL,
    email       VARCHAR2(150)  NOT NULL UNIQUE,
    rut         VARCHAR2(12)   NOT NULL UNIQUE
);

-- Tabla de Prestamos
CREATE TABLE prestamos (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id       NUMBER        NOT NULL,
    titulo_libro     VARCHAR2(200) NOT NULL,
    autor            VARCHAR2(150) NOT NULL,
    fecha_prestamo   DATE          NOT NULL,
    fecha_devolucion DATE,
    estado           VARCHAR2(20)  NOT NULL,
    CONSTRAINT fk_prestamo_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuarios(id),
    CONSTRAINT chk_estado CHECK (estado IN ('ACTIVO', 'DEVUELTO'))
);

-- Datos de prueba
INSERT INTO usuarios (nombre, apellido, email, rut)
VALUES ('Juan', 'Gonzalez', 'juan.gonzalez@correo.cl', '12345678-9');

INSERT INTO usuarios (nombre, apellido, email, rut)
VALUES ('Maria', 'Lopez', 'maria.lopez@correo.cl', '98765432-1');

INSERT INTO prestamos (usuario_id, titulo_libro, autor, fecha_prestamo, fecha_devolucion, estado)
VALUES (1, 'Clean Code', 'Robert C. Martin', TO_DATE('2024-03-01', 'YYYY-MM-DD'), NULL, 'ACTIVO');

INSERT INTO prestamos (usuario_id, titulo_libro, autor, fecha_prestamo, fecha_devolucion, estado)
VALUES (2, 'The Pragmatic Programmer', 'David Thomas', TO_DATE('2024-02-15', 'YYYY-MM-DD'), TO_DATE('2024-03-01', 'YYYY-MM-DD'), 'DEVUELTO');

COMMIT;
